# Generated by Django 5.2.1 on 2025-05-17 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.TextField(verbose_name='Название файла')),
                ('file_path', models.TextField(unique=True, verbose_name='Путь к файлу')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Содержимое')),
                ('tsv', models.TextField(blank=True, null=True, verbose_name='TSVECTOR')),
                ('faculty', models.TextField(verbose_name='Факультет')),
                ('education_level', models.CharField(choices=[('bachelor', 'Бакалавриат'), ('master', 'Магистратура'), ('phd', 'Аспирантура')], max_length=20, verbose_name='Уровень образования')),
                ('admission_year', models.IntegerField(verbose_name='Год поступления')),
                ('study_field', models.TextField(verbose_name='Направление подготовки')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'db_table': 'documents_2',
                'managed': False,
            },
        ),
    ]
